version: "3.6"
services:
    app:
        build:
            context: ./docker/php
            args:
                - TZ=${TZ}
                - PROXY_HOST=${PROXY_HOST}
                - PROXY_PORT=${PROXY_PORT}
                - PROXY_USER=${PROXY_USER}
                - PROXY_PASSWORD=${PROXY_PASSWORD}
                - PROXY_PASSWORD_ENCODING=${PROXY_PASSWORD_ENCODING}
        container_name: laravel_app
        networks: 
            - external-link
            - internal-link
        volumes:
            - ./src:/work
            - ./logs:/work/storage/logs
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/cacert.pem:/work/cacert.pem
        working_dir: /work
        environment:
            - TZ=${TZ}
            - HTTP_PROXY=http://${PROXY_USER}:${PROXY_PASSWORD_ENCODING}@${PROXY_HOST}:${PROXY_PORT}
            - HTTPS_PROXY=http://${PROXY_USER}:${PROXY_PASSWORD_ENCODING}@${PROXY_HOST}:${PROXY_PORT}
    web:
        image: nginx:1.17-alpine
        container_name: laravel_web
        networks: 
            - internal-link
        depends_on:
            - app
        ports:
            - 10080:80
            - 10443:443
        volumes:
            - ./src:/work
            - ./logs:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        environment:
            - TZ=${TZ}
networks: 
    default:
        external: 
            name: bridge
    internal-link:
        name: laravel_network
    external-link:
        external: 
            name: wp_network